name: Ember test audit
on: pull_request

jobs:
  time-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: nanasess/setup-chromedriver@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cd ui && yarn --frozen-lockfile
      - name: Audit tests
        shell: bash
        working-directory: ui
        run: "echo \"::add-path::./node_modules/.bin\""
      - run: echo $PATH
      - run: mkdir -p /tmp/test-reports
      - run: cd ui && npx github:backspace/ember-test-audit#json 3 --json
      - run: mv ui/test-timings* master-audit.txt
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: master-audit
          path: master-audit.txt
  time-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: cd ui && yarn --frozen-lockfile
      - name: Audit tests
        shell: bash
        working-directory: ui
        run: "echo \"::add-path::./node_modules/.bin\""
      - run: echo $PATH
      - run: mkdir -p /tmp/test-reports
      - run: cd ui && npx github:backspace/ember-test-audit#json 3 --json
      - run: mv ui/test-timings* pr-audit.txt
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: pr-audit
          path: pr-audit.txt
  compare:
    needs: [time-master, time-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: master-audit
      - uses: actions/download-artifact@v2
        with:
          name: pr-audit
      - uses: backspace/ember-test-audit-comparison-action@primary
          with:
            base-report-path: master-audit.txt
            comparison-report-path: pr-audit.txt
            base-identifier: master # FIXME could be something else
            comparison-identifier: ${{ github.event.pull_request.base.sha }} # FIXME restore truncation?
            output-path: audit-diff.txt
      - uses: marocchino/sticky-pull-request-comment@33a6cfb
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: audit-diff.txt
