name: Ember test audit comparison
on: pull_request

defaults:
  run:
    working-directory: ui

jobs:
  time-master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.sha }}
      - uses: nanasess/setup-chromedriver@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn --frozen-lockfile
      - run: echo $PATH
      - run: mkdir -p /tmp/test-reports
      - run: npx github:backspace/ember-test-audit#json 1 lifecycle --json
      - run: mv test-timings* master-audit.txt
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: master-audit
          path: master-audit.txt
  time-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - run: yarn --frozen-lockfile
      - run: echo $PATH
      - run: mkdir -p /tmp/test-reports
      - run: npx github:backspace/ember-test-audit#json 1 lifecycle --json
      - run: mv test-timings* pr-audit.txt
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: pr-audit
          path: pr-audit.txt
  compare:
    needs: [time-master, time-pr]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: master-audit
      - uses: actions/download-artifact@v2
        with:
          name: pr-audit
      - uses: backspace/ember-test-audit-comparison-action@primary
        with:
          base-report-path: master-audit.txt
          comparison-report-path: pr-audit.txt
          base-identifier: ${{ github.event.pull_request.base.ref }}
          comparison-identifier: ${{ github.event.pull_request.head.sha }}
          output-path: audit-diff.txt
      - uses: marocchino/sticky-pull-request-comment@33a6cfb
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          path: audit-diff.txt
